# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 00:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='time_stamp',
        ),
    ]
