# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 01:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(180)])),
                ('location', models.CharField(max_length=80, null=True)),
                ('location_option', models.CharField(choices=[('TUTOR_ADDRESS', "Tutor's address"), ('USER_ADDRESS', "User's address"), ('OTHER', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REQUESTED', 'Requested'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=10)),
                ('tutor_comments', models.CharField(default='No tutor comments.', max_length=500)),
                ('user_comments', models.CharField(default='No user comments.', max_length=500)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.Tutor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
